### ISSUE TITLE
Auth login failing silently

### ISSUE THREAD

**Issue by dylonion** [dylonion/Standups#1]
Auth register appears to create a new user properly. They appear in database. But upon login, auth passes from /login into redirect to /verify (as expected), and then fails to retrieve a user. Because this is a magic 'auth' method, I am unable to add console logs at any stage of the process that actually appear in server logs. It simply retrieves null values for user email, name, etc.

The issue is somehow related to me changing my login method to not have a username - rather rely simply on email address. I know this because it is identical to the auth I set up for the (working) focus groups project 3, other than the modifications I tried to make to the users table and corresponding methods.

**Comment by jlr7245** [comment]
Yea, it does that, it's a passport thing. You need to pass what fields are being used for auth in when you set up passport. [Check this out](http://www.passportjs.org/docs/username-password/) -- the "parameters" section.
